apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermariogitopsproject-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: supermariogitopsproject
  template:
    metadata:
      labels:
        app: supermariogitopsproject  
    spec:
      containers: 
      - name: supermariogitopsproject-container
        image: docker.io/nehas1908/supermariogitopsproject:v8
        ports:
        - containerPort: 8080 # Informational and for readability , hence this must match the port the actual application inside your container is configured to bind to and listen on.
---

apiVersion: v1
kind: Service
metadata:
  name: supermariogitopsproject-service
spec:
  selector:
    app: supermariogitopsproject
  ports:
    - protocol: TCP
      port: 80 # service port on which url will be accessible externally.
      targetPort: 8080  # The Service's targetPort must target the port where the application is actually running. 
  type: LoadBalancer