apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermariogitopsproject-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: supermariogitopsproject
  template:
    metadata:
      labels:
        app: supermariogitopsproject  
    spec:
      containers: 
      - name: supermariogitopsproject-container
        image: docker.io/nehas1908/supermariogitopsproject:v2
        ports:
        - containerPort: 8080 # Informational, matches the application port for developer's reference. This is not the port that will be exposed externally. 
---

apiVersion: v1
kind: Service
metadata:
  name: supermariogitopsproject-service
spec:
  selector:
    app: supermariogitopsproject
  ports:
    - protocol: TCP
      port: 80 # service port on which url will be accessible externally.
      targetPort: 8080  # Pod port mapping for request hopping. MUST match the actual internal application port
  type: LoadBalancer